name: mera-store-infra

services:
  logging-api:
    container_name: logging-api
    image: ${DOCKER_REGISTRY-}merastore.service.logging.api:1.0.0
    build:
      context: ../../logging-service # Update path to your Dockerfile
      dockerfile: src/MeraStore.Service.Logging.Api/Dockerfile # Name of the Dockerfile
      args:
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    ports:
      - "8101:8101" # Expose the API on port 8101 to the host's port 8101
    networks:
      - msec-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NUGET_PASSWORD=${NUGET_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8101
      - ConnectionStrings__LoggingDb=Server=database;Database=Logging;User Id=mera-store-logging;Password=J6k*9Pt@X2v#1Qc$;Encrypt=False;TrustServerCertificate=True # Set your DB connection string
      - Consul__Host=consul-app
      - Consul__Discovery__Port=8101
      
networks:
  msec-net:
    driver: bridge