name: mera-store-infra

services:
  logging-api:
    container_name: logging-api
    image: ${DOCKER_REGISTRY-}merastore.service.logging.api:1.0.0
    
    build:
      context: ../../logging-service # Update path to your Dockerfile
      dockerfile: src/MeraStore.Service.Logging.Api/Dockerfile # Name of the Dockerfile
      args:
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    ports:
      - "8101:8101" # Expose the API on port 8101 to the host's port 8101
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NUGET_PASSWORD=${NUGET_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8101
      - ConnectionStrings__LoggingDb=Server=database;Database=Logging;User Id=mera-store-logging;Password=L0gG!ngP@ssw0rd2024$;Encrypt=False;TrustServerCertificate=True # Set your DB connection string