services:
  # database:
    # container_name: database
    # image: mcr.microsoft.com/mssql/server:latest
    # environment:
      # SA_PASSWORD: "SwN12345678"
      # ACCEPT_EULA: "Y"
    # restart: always
    # ports:
      # - "1433:1433"

  elastic.search:
    container_name: elastic.search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - node.name=elastic.search
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - msec-net
    volumes:
      - share-data:/usr/share/elasticsearch/data 
    ports:
      - "9200:9200"

  redis.cache:
    image: redis:latest
    container_name: redis.cache
    restart: always
    ports:
      - "6379:6379"
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.15.1
    environment:
      - ELASTICSEARCH_URL=http://elastic.search:9200
      - ELASTICSEARCH_HOSTS=http://elastic.search:9200
    networks:
      - msec-net
    depends_on:
      - elastic.search
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data  # Persistent volume for Kibana
  
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - msec-net
      
volumes:
  share-data:
    driver: local
  kibana-data:  # Declare the volume for Kibana
    driver: local
  jenkins-data:
    driver: local

networks:
  msec-net:
    driver: bridge
